#!/bin/sh

if [ "$1" = "" ]; then
 maim -d 0 | xclip -selection clipboard -t image/png
elif [ "$1" = "-s" ]; then
 maim -s | xclip -selection clipboard -t image/png
elif [ "$1" = "-w" ]; then
 maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
else
 echo "unknown argument"
fi
